# Generated by Django 6.0.2 on 2026-03-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_remove_inquiry_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='country',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
