# Generated by Django 5.2 on 2025-05-07 16:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
