# Generated by Django 6.0.2 on 2026-02-18 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0011_whyus_experience_whyus_image_icon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
        migrations.DeleteModel(
            name='Goals',
        ),
        migrations.DeleteModel(
            name='LegalDocument',
        ),
        migrations.DeleteModel(
            name='RecruitmentProcess',
        ),
        migrations.DeleteModel(
            name='Vision',
        ),
    ]
