# Generated by Django 6.0.2 on 2026-03-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0012_delete_companyprofile_delete_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='students_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='about'),
        ),
    ]
