# Generated by Django 6.0.2 on 2026-03-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='flat',
            new_name='flag',
        ),
    ]
